services:
  db:
    restart: "no"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
      - "35729:35729" # Spring DevTools LiveReload
    build:
      context: ./url-shortener
      target: dev
    # command: mvn spring-boot:run
    volumes:
      - m2_cache:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_ADD_PROPERTIES=true
      - SPRING_DEVTOOLS_RESTART_TRIGGER_FILE=.reloadtrigger
    develop:
      watch:
        - path: ./url-shortener/src
          action: sync
          target: /app/src
          ignore:
            - ./url-shortener/src/test
        - path: ./url-shortener/pom.xml
          action: rebuild

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  frontend:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
    networks:
      - default

  playwright:
    build:
      context: ./frontend
      dockerfile: Dockerfile.playwright
      args:
        - VITE_API_URL=http://backend:8000
        - NODE_ENV=production
    ipc: host
    depends_on:
      - backend
      - mailcatcher
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:8000
      - MAILCATCHER_HOST=http://mailcatcher:1080
      # For the reports when run locally
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
      - CI=${CI}
    volumes:
      - ./frontend/blob-report:/app/blob-report
      - ./frontend/test-results:/app/test-results
    ports:
      - 9323:9323
    networks:
      - default

volumes:
  m2_cache:
