services:
  # TODO: use docker secrets to manage the passwords
  proxy:
    image: traefik:3.3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik/config/static.dev.yml:/etc/traefik/traefik.yml:ro
      - ./infra/traefik/config/dynamic.dev.yml:/etc/traefik/dynamic/dynamic.yml:ro
      # TODO: use secrets to add the hashed password
      - ./infra/traefik/usersfile:/etc/traefik/usersfile:ro
      - ./certs:/etc/certs:ro
      - ./infra/traefik/logs:/var/log/traefik
      - proxy-public-certificates:/certificates
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env.dev
    networks:
      - proxy-public
    labels:
      - "traefik.constraint-label=traefik-public"
      - "traefik.enable=true"

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./infra/prometheus/staging.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - proxy-public
    labels:
      - "traefik.constraint-label=traefik-public"
      - "traefik.enable=true"

  grafana:
    image: grafana/grafana:latest
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/grafana/provisioning/datasources/prometheus.staging.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - proxy-public
    labels:
      - "traefik.constraint-label=traefik-public"
      - "traefik.enable=true"

  db:
    env_file:
      - .env.dev

  adminer:
    restart: always
    networks:
      - proxy-public
      - default
    labels:
      - "traefik.constraint-label=traefik-public"
      - "traefik.enable=true"

  frontend:
    restart: always
    env_file:
      - .env.dev
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://api.${DOMAIN?Variable not set}
        - NODE_ENV=production
    networks:
      - proxy-public
    labels:
      - "traefik.constraint-label=traefik-public"
      - "traefik.enable=true"

  backend:
    restart: always
    build:
      context: ./url-shortener
      target: release
    env_file:
      - .env.dev
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    networks:
      - proxy-public
      - default
    labels:
      - "traefik.constraint-label=traefik-public"
      - "traefik.enable=true"

volumes:
  proxy-public-certificates:
  grafana-data:
  prometheus-data:

networks:
  proxy-public:
    external: true
# secrets:
#   proxy-usersfile:
#     file: ./infra/traefik/usersfile
