/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * RESTful API for URL shortening service. Provides endpoints for URL shortening, redirection, user management, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type UrlUpdateRequestStatus =
	(typeof UrlUpdateRequestStatus)[keyof typeof UrlUpdateRequestStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UrlUpdateRequestStatus = {
	ACTIVE: "ACTIVE",
	INACTIVE: "INACTIVE",
} as const
