/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * RESTful API for URL shortening service. Provides endpoints for URL shortening, redirection, user management, and analytics.
 * OpenAPI spec version: 1.0.0
 */

export type UserResponseDTOProvider =
	(typeof UserResponseDTOProvider)[keyof typeof UserResponseDTOProvider]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseDTOProvider = {
	LOCAL: "LOCAL",
	GOOGLE: "GOOGLE",
	GITHUB: "GITHUB",
} as const
