/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * RESTful API for URL shortening service. Provides endpoints for URL shortening, redirection, user management, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseDTOProvider } from "./userResponseDTOProvider"
import type { UserResponseDTORole } from "./userResponseDTORole"

export interface UserResponseDTO {
	id?: string
	email?: string
	name?: string
	provider?: UserResponseDTOProvider
	providerId?: string
	avatarUrl?: string
	role?: UserResponseDTORole
	createdAt?: string
	canChangePassword?: boolean
}
