/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * URL Shortener API
 * RESTful API for URL shortening service. Provides endpoints for URL shortening, redirection, user management, and analytics.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query"
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query"

import type {
	CheckFeatureFlag200,
	GetAllFeatureFlags200,
	GetCommonFeatureFlags200,
} from "../../schemas"

import { customInstance } from ".././mutator/customAxiosInstance"
import type { ErrorType } from ".././mutator/customAxiosInstance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Check if a specific feature flag is enabled
 * @summary Check feature flag status
 */
export const checkFeatureFlag = (
	featureName: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CheckFeatureFlag200>(
		{ url: `/api/features/${featureName}`, method: "GET", signal },
		options,
	)
}

export const getCheckFeatureFlagQueryKey = (featureName: string) => {
	return [`/api/features/${featureName}`] as const
}

export const getCheckFeatureFlagQueryOptions = <
	TData = Awaited<ReturnType<typeof checkFeatureFlag>>,
	TError = ErrorType<unknown>,
>(
	featureName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof checkFeatureFlag>>,
				TError,
				TData
			>
		>
		request?: SecondParameter<typeof customInstance>
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {}

	const queryKey =
		queryOptions?.queryKey ?? getCheckFeatureFlagQueryKey(featureName)

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof checkFeatureFlag>>
	> = ({ signal }) => checkFeatureFlag(featureName, requestOptions, signal)

	return {
		queryKey,
		queryFn,
		enabled: !!featureName,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof checkFeatureFlag>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckFeatureFlagQueryResult = NonNullable<
	Awaited<ReturnType<typeof checkFeatureFlag>>
>
export type CheckFeatureFlagQueryError = ErrorType<unknown>

export function useCheckFeatureFlag<
	TData = Awaited<ReturnType<typeof checkFeatureFlag>>,
	TError = ErrorType<unknown>,
>(
	featureName: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof checkFeatureFlag>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof checkFeatureFlag>>,
					TError,
					Awaited<ReturnType<typeof checkFeatureFlag>>
				>,
				"initialData"
			>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useCheckFeatureFlag<
	TData = Awaited<ReturnType<typeof checkFeatureFlag>>,
	TError = ErrorType<unknown>,
>(
	featureName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof checkFeatureFlag>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof checkFeatureFlag>>,
					TError,
					Awaited<ReturnType<typeof checkFeatureFlag>>
				>,
				"initialData"
			>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useCheckFeatureFlag<
	TData = Awaited<ReturnType<typeof checkFeatureFlag>>,
	TError = ErrorType<unknown>,
>(
	featureName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof checkFeatureFlag>>,
				TError,
				TData
			>
		>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Check feature flag status
 */

export function useCheckFeatureFlag<
	TData = Awaited<ReturnType<typeof checkFeatureFlag>>,
	TError = ErrorType<unknown>,
>(
	featureName: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof checkFeatureFlag>>,
				TError,
				TData
			>
		>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getCheckFeatureFlagQueryOptions(featureName, options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	query.queryKey = queryOptions.queryKey

	return query
}

/**
 * Get the status of commonly used feature flags for frontend integration
 * @summary Get common feature flags
 */
export const getCommonFeatureFlags = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetCommonFeatureFlags200>(
		{ url: `/api/features/common`, method: "GET", signal },
		options,
	)
}

export const getGetCommonFeatureFlagsQueryKey = () => {
	return [`/api/features/common`] as const
}

export const getGetCommonFeatureFlagsQueryOptions = <
	TData = Awaited<ReturnType<typeof getCommonFeatureFlags>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getCommonFeatureFlags>>,
			TError,
			TData
		>
	>
	request?: SecondParameter<typeof customInstance>
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetCommonFeatureFlagsQueryKey()

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getCommonFeatureFlags>>
	> = ({ signal }) => getCommonFeatureFlags(requestOptions, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getCommonFeatureFlags>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCommonFeatureFlagsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getCommonFeatureFlags>>
>
export type GetCommonFeatureFlagsQueryError = ErrorType<unknown>

export function useGetCommonFeatureFlags<
	TData = Awaited<ReturnType<typeof getCommonFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommonFeatureFlags>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCommonFeatureFlags>>,
					TError,
					Awaited<ReturnType<typeof getCommonFeatureFlags>>
				>,
				"initialData"
			>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCommonFeatureFlags<
	TData = Awaited<ReturnType<typeof getCommonFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommonFeatureFlags>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCommonFeatureFlags>>,
					TError,
					Awaited<ReturnType<typeof getCommonFeatureFlags>>
				>,
				"initialData"
			>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetCommonFeatureFlags<
	TData = Awaited<ReturnType<typeof getCommonFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommonFeatureFlags>>,
				TError,
				TData
			>
		>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get common feature flags
 */

export function useGetCommonFeatureFlags<
	TData = Awaited<ReturnType<typeof getCommonFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommonFeatureFlags>>,
				TError,
				TData
			>
		>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetCommonFeatureFlagsQueryOptions(options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	query.queryKey = queryOptions.queryKey

	return query
}

/**
 * Get the status of all feature flags (admin only)
 * @summary Get all feature flags
 */
export const getAllFeatureFlags = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetAllFeatureFlags200>(
		{ url: `/api/features/`, method: "GET", signal },
		options,
	)
}

export const getGetAllFeatureFlagsQueryKey = () => {
	return [`/api/features/`] as const
}

export const getGetAllFeatureFlagsQueryOptions = <
	TData = Awaited<ReturnType<typeof getAllFeatureFlags>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getAllFeatureFlags>>,
			TError,
			TData
		>
	>
	request?: SecondParameter<typeof customInstance>
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {}

	const queryKey = queryOptions?.queryKey ?? getGetAllFeatureFlagsQueryKey()

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getAllFeatureFlags>>
	> = ({ signal }) => getAllFeatureFlags(requestOptions, signal)

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getAllFeatureFlags>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllFeatureFlagsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getAllFeatureFlags>>
>
export type GetAllFeatureFlagsQueryError = ErrorType<unknown>

export function useGetAllFeatureFlags<
	TData = Awaited<ReturnType<typeof getAllFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAllFeatureFlags>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllFeatureFlags>>,
					TError,
					Awaited<ReturnType<typeof getAllFeatureFlags>>
				>,
				"initialData"
			>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllFeatureFlags<
	TData = Awaited<ReturnType<typeof getAllFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAllFeatureFlags>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getAllFeatureFlags>>,
					TError,
					Awaited<ReturnType<typeof getAllFeatureFlags>>
				>,
				"initialData"
			>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
export function useGetAllFeatureFlags<
	TData = Awaited<ReturnType<typeof getAllFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAllFeatureFlags>>,
				TError,
				TData
			>
		>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
}
/**
 * @summary Get all feature flags
 */

export function useGetAllFeatureFlags<
	TData = Awaited<ReturnType<typeof getAllFeatureFlags>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getAllFeatureFlags>>,
				TError,
				TData
			>
		>
		request?: SecondParameter<typeof customInstance>
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>
} {
	const queryOptions = getGetAllFeatureFlagsQueryOptions(options)

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> }

	query.queryKey = queryOptions.queryKey

	return query
}
