tls:
  certificates:
    - certFile: /etc/certs/traefik.dev.tinyls.com+4.pem
      keyFile: /etc/certs/traefik.dev.tinyls.com+4-key.pem
      stores:
        - default

http:
  middlewares:
    dashboard-auth:
      basicAuth:
        realm: "Traefik Dashboard"
        removeHeader: true
        usersFile: "/etc/traefik/usersfile"

    # Limit each client IP to 100 requests/second, with a burst of 50
    global-rate-limit:
      rateLimit:
        average: 100 # sustained rate per second
        burst: 50 # maximum spike

    # Redirect plain HTTP → HTTPS
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    # Rewrite single-segment shortcodes into backend API path
    rewrite-shortcode:
      replacePathRegex:
        regex: "^/([A-Za-z0-9_-]+)$"
        replacement: "/api/urls/r/$1"
    
    shortcode-frontend-fallback:
      errors:
        status:
          - "404"
        service: tinyls-dev-frontend
        # serve the SPA entrypoint; your React app will see the original path
        query: "/"

  routers:
    # Traefik Dashboard configuration
    dashboard:
      rule: Host(`traefik.dev.tinyls.com`)
      service: api@internal
      entryPoints:
        - websecure
      middlewares:
        - dashboard-auth
      tls: {}

    # Grafana UI configuration
    grafana:
      rule: Host(`grafana.dev.tinyls.com`)
      service: grafana
      entryPoints:
        - websecure
      tls: {}

    # Adminer HTTP -> HTTP configuration
    tinyls-dev-adminer-http:
      rule: Host(`adminer.dev.tinyls.com`)
      service: tinyls-dev-adminer
      entryPoints:
        - web
      middlewares:
        - https-redirect
        - global-rate-limit

    tinyls-dev-adminer-https:
      rule: Host(`adminer.dev.tinyls.com`)
      service: tinyls-dev-adminer
      entryPoints:
        - websecure
      middlewares:
        - global-rate-limit
      tls: {}

    # Backend API (HTTP -> HTTPS) configuration
    tinyls-dev-backend-http:
      rule: Host(`api.dev.tinyls.com`) && (
        PathPrefix(`/api`) ||
        PathPrefix(`/api-docs`) ||
        PathPrefix(`/swagger-ui`)
        )
      service: tinyls-dev-backend
      entryPoints:
        - web
      middlewares:
        - https-redirect
        - global-rate-limit
      priority: 30

    tinyls-dev-backend-https:
      rule: Host(`api.dev.tinyls.com`) &&(
        PathPrefix(`/api`) ||
        PathPrefix(`/api-docs`) ||
        PathPrefix(`/swagger-ui`)
        )
      service: tinyls-dev-backend
      entryPoints:
        - websecure
      middlewares:
        - global-rate-limit
      tls: {}
      priority: 30

    # Backend Auth router for OAuth
    tinyls-dev-backend-auth-http:
      rule: Host(`api.dev.tinyls.com`) &&
        (
        PathPrefix(`/oauth2/authorize`) ||
        PathPrefix(`/login/oauth2/code`)
        )
      service: tinyls-dev-backend
      entryPoints:
        - web
      middlewares:
        - global-rate-limit
        - https-redirect
      priority: 25

    tinyls-dev-backend-auth-https:
      rule: Host(`api.dev.tinyls.com`) &&
        (
        PathPrefix(`/oauth2/authorize`) ||
        PathPrefix(`/login/oauth2/code`)
        )
      service: tinyls-dev-backend
      entryPoints:
        - websecure
      middlewares:
        - global-rate-limit
      tls: {}
      priority: 25

    tinyls-dev-callback-http:
      rule: Host(`dev.tinyls.com`) && (PathPrefix(`/oauth2-callback`) || PathPrefix(`/login`) || PathPrefix(`/register`))
      service: tinyls-dev-frontend
      entryPoints:
        - web
      middlewares:
        - https-redirect
        - global-rate-limit
      priority: 25

    tinyls-dev-callback-https:
      rule: Host(`dev.tinyls.com`) && (PathPrefix(`/oauth2-callback`) || PathPrefix(`/login`) || PathPrefix(`/register`))
      service: tinyls-dev-frontend
      entryPoints:
        - websecure
      middlewares:
        - global-rate-limit
      tls: {}
      priority: 25

    # Shortcode redirect (HTTP -> HTTPS) configuration
    tinyls-dev-shortcode-http:
      rule: Host(`dev.tinyls.com`) && PathRegexp(`^/[A-Za-z0-9_-]+$`)
      service: tinyls-dev-backend
      entryPoints:
        - web
      middlewares:
        - https-redirect
        - global-rate-limit
      priority: 20

    tinyls-dev-shortcode-https:
      rule: Host(`dev.tinyls.com`) && PathRegexp(`^/[A-Za-z0-9_-]+$`)
      service: tinyls-dev-backend
      entryPoints:
        - websecure
      middlewares:
        - rewrite-shortcode # turn /abc → /api/r/abc
        - global-rate-limit
        - shortcode-frontend-fallback # any 404 -> frontend
      tls: {}
      priority: 20

    # Frontend SPA (HTTP -> HTTPS) configuration
    tinyls-dev-frontend-http:
      rule: Host(`dev.tinyls.com`)
      service: tinyls-dev-frontend
      entryPoints:
        - web
      middlewares:
        - https-redirect
        - global-rate-limit
      priority: 10

    # Frontend HTTPS configuration
    tinyls-dev-frontend-https:
      rule: Host(`dev.tinyls.com`)
      service: tinyls-dev-frontend
      entryPoints:
        - websecure
      middlewares:
        - global-rate-limit
      tls: {}
      priority: 10

  services:
    prometheus:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    tinyls-dev-adminer:
      loadBalancer:
        servers:
          - url: "http://adminer:8080"

    tinyls-dev-backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    tinyls-dev-frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"

    shortcode-redirect-service:
      loadBalancer:
        servers:
          - url: "http://backend:8000/api/urls/r/"
        passHostHeader: true
